pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your version control system
                checkout scm
            }
        }

        stage('Build Docker Image and push to ecr') {
            steps {
                script {
                    // Build the Docker image
                   sh '''
            cd ./sih-project/
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q6a6x9j2
            docker build -t sih .
            docker tag sih:latest public.ecr.aws/q6a6x9j2/sih:latest
            docker push public.ecr.aws/q6a6x9j2/sih:latest
            '''
                }
            }
        }

        // stage('Deploy to Kubernetes') {
        //     steps {
        //         script {
        //             // Deploy the Docker image to your Kubernetes cluster (replace with your kubectl configuration)
        //             // sh 'kubectl apply -f kubernetes-deployment.yaml'
        //             echo "success"
        //         }
        //     }
        // }
    }
}
